name: API - Build, Push (GHCR) & Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/secretaria-concafras-api:latest

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Encontra o .csproj (prioriza caminhos com "api")
      - name: Find .csproj
        id: findproj
        shell: bash
        run: |
          set -e
          mapfile -t ALL < <(git ls-files '**/*.csproj')
          if [ ${#ALL[@]} -eq 0 ]; then echo "Nenhum .csproj encontrado."; exit 1; fi
          PICK=""
          for p in "${ALL[@]}"; do
            if echo "$p" | grep -i -q "/api"; then PICK="$p"; break; fi
          done
          if [ -z "$PICK" ]; then PICK="${ALL[0]}"; fi
          DIR="$(dirname "$PICK")"
          DLL="$(basename "$PICK" .csproj).dll"
          echo "proj_path=$PICK" >> "$GITHUB_OUTPUT"
          echo "proj_dir=$DIR" >> "$GITHUB_OUTPUT"
          echo "dll_name=$DLL" >> "$GITHUB_OUTPUT"
          echo "Usando projeto: $PICK (DLL: $DLL)"

      # Detecta versão do .NET pelo global.json (se existir)
      - name: Detect .NET SDK version
        id: dotnetver
        shell: bash
        run: |
          set -e
          SDK="8.0.x"
          if [ -f global.json ]; then
            sudo apt-get update -y && sudo apt-get install -y jq
            SDK="$(jq -r '.sdk.version // empty' global.json)"
            [ -z "$SDK" ] && SDK="8.0.x"
          fi
          RUNTIME_TAG="$(echo "$SDK" | awk -F. '{print $1"."$2}')"
          echo "sdk=$SDK" >> "$GITHUB_OUTPUT"
          echo "runtime_tag=$RUNTIME_TAG" >> "$GITHUB_OUTPUT"
          echo "SDK: $SDK | RUNTIME: $RUNTIME_TAG"

      - name: Setup .NET (${{ steps.dotnetver.outputs.sdk }})
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ steps.dotnetver.outputs.sdk }}

      # Restaura e publica no runner (fora do Docker)
      - name: Restore
        run: dotnet restore "${{ steps.findproj.outputs.proj_path }}"
      - name: Publish (Release)
        run: dotnet publish "${{ steps.findproj.outputs.proj_path }}" -c Release -o ./.out/publish /p:UseAppHost=false

      # Gera um Dockerfile de runtime leve
      - name: Generate runtime Dockerfile
        run: |
          cat > Dockerfile.runtime <<'DOCKER'
          FROM mcr.microsoft.com/dotnet/aspnet:RUNTIME_TAG
          WORKDIR /app
          COPY ./.out/publish .
          ENV ASPNETCORE_URLS=http://+:8080
          EXPOSE 8080
          ENTRYPOINT ["dotnet","DLL_PLACEHOLDER"]
          DOCKER
          sed -i "s/RUNTIME_TAG/${{ steps.dotnetver.outputs.runtime_tag }}/" Dockerfile.runtime
          sed -i "s/DLL_PLACEHOLDER/${{ steps.findproj.outputs.dll_name }}/" Dockerfile.runtime
          echo "---- Dockerfile.runtime ----"
          sed -n '1,120p' Dockerfile.runtime

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.runtime
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Deploy to VPS (compose pull/up)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          port: 22
          script: |
            set -e
            # Se o pacote no GHCR for PRIVADO, descomente o login abaixo e crie GHCR_USERNAME/GHCR_TOKEN nos secrets:
            # echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
            cd /root/apps/secretaria-concafras
            docker compose --env-file .env pull api
            docker compose --env-file .env up -d api
            docker image prune -f
